### PR TITLE
Ditch unnecessary print

### PR DESCRIPTION
**Pull request by DrMurx**
#### General

- [x] Update Changelog following the conventions laid out on [Keep A Changelog](http://keepachangelog.com/)

- [x] ~Update README with any necessary configuration snippets~

- [x] ~Binstubs are created if needed~

- [x] RuboCop passes (it passes on the line i've removed 😄 )

- [x] ~Existing tests pass~

#### Purpose

An unnecessary print of the sensor values prevented that the check output starts with `OK`, `WARNING` or `CRITICAL`.

### CODE REVIEW

**Comment by GhostLyrics** [comment]
Looks good to me.

```plain
user@host:~path$ /opt/sensu/embedded/bin/ruby check-temperature.rb
[24.0, 79.0, 89.0][28.0, 79.0, 89.0][26.0, 79.0, 89.0][24.0, 79.0, 89.0][22.0, 79.0, 89.0][24.0, 79.0, 89.0]CheckTemperature OK: All sensors are reporting safe temperature readings.

user@host:~path$ git checkout -b DrMurx-fix_debug_output master
Switched to a new branch 'DrMurx-fix_debug_output'
user@host:~path$ git pull https://github.com/DrMurx/sensu-plugins-environmental-checks.git fix_debug_output
[omitted]

user@host:~path$ /opt/sensu/embedded/bin/ruby check-temperature.rb
CheckTemperature OK: All sensors are reporting safe temperature readings.
```

**Comment by GhostLyrics** [comment]
If I may suggest one tiny thing to make your PR better - reword the Changelog entry to something along the lines of "remove unnecessary…" instead of something as negative as "spoil". *I realize you might feel that way but we'd really prefer to stay friendly to all (current and past) contributors.* 😄

**Comment by DrMurx** [comment]
Oh yes, you're completely right. :)

**Comment by GhostLyrics** [comment]
Thank you for your contribution. 😄

**Comment by DrMurx** [comment]
@GhostLyrics Would you mind tagging a new release then?

**Comment by majormoses** [comment]
I have sent @GhostLyrics instructions on how to do it, I will give it a day or so (to account for TZ differences) and if it is not released I will do it but I would prefer teaching people to fish than give them fish.

**Comment by majormoses** [comment]
released: https://rubygems.org/gems/sensu-plugins-environmental-checks/versions/1.2.0

**Pull request merged**
